# -*- coding: utf-8 -*-
"""INSURANCE_APP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S-lHfQWkuZ-Gj3M6C-Gz-qpFaD7HRdlV
"""


import streamlit as st
import numpy as np
import pickle
from streamlit_chat import message

# ---------------------- PAGE CONFIG (Must be at the very top) ----------------------
st.set_page_config(page_title="💼 Insurance Predictor", layout="centered", page_icon="💰")

# ---------------------- LOAD MODEL ----------------------
@st.cache_resource
def load_model():
    with open('insurance_model.pkl', 'rb') as f:
        return pickle.load(f)

model = load_model()

# ---------------------- HEADER & MOVING BANNER ----------------------
st.markdown("""
    <style>
        .banner {
            background-color: #D1ECF1;
            color: #0C5460;
            padding: 10px;
            border-radius: 10px;
            text-align: center;
            animation: moveBanner 15s linear infinite;
            font-size: 16px;
        }
        @keyframes moveBanner {
            0% {transform: translateX(-100%);}
            50% {transform: translateX(0);}
            100% {transform: translateX(100%);}
        }
        .title {
            font-size: 40px;
            color: #4B8BBE;
            text-align: center;
            font-weight: bold;
        }
        .subtitle {
            font-size: 18px;
            color: #666;
            text-align: center;
        }
    </style>
    <div class="title">💰 Insurance Charges Estimator</div>
    <div class="subtitle">Predict medical expenses using smart ML technology</div>
    <br>
    <div class="banner">📢 Estimate Charges Instantly | Built with ❤️ by konjam_kadhalxx | Streamlit Pro UI 🌟</div>
""", unsafe_allow_html=True)

# ---------------------- FORM ----------------------
with st.form("prediction_form", clear_on_submit=False):
    st.subheader("🧾 Enter Your Information")

    col1, col2 = st.columns(2)

    with col1:
        age = st.slider("🎂 Age", 18, 100, 30)
        bmi = st.number_input("⚖️ BMI (Body Mass Index)", 10.0, 50.0, value=25.0)
        children = st.number_input("👶 Children", 0, 10, step=1)

    with col2:
        sex = st.radio("🧑 Sex", ['Male', 'Female'], horizontal=True)
        smoker = st.radio("🚬 Smoker", ['Yes', 'No'], horizontal=True)

    # Convert to model-expected format
    sex = 1 if sex == "Male" else 0
    smoker = 1 if smoker == "Yes" else 0

    submitted = st.form_submit_button("🔍 Estimate Charges")
    if submitted:
        input_data = np.array([[age, sex, bmi, children, smoker]])
        result = model.predict(input_data)[0]
        st.success(f"💸 Estimated Charges: **${result:,.2f}**")

# ---------------------- CHATBOT ----------------------
st.markdown("---")
st.subheader("💬 Insurance ChatBot Assistant")

# Sample static Q&A
default_qa = {
    "What factors affect insurance charges?": "Age, sex, BMI, number of children, and smoking status.",
    "Why is smoking expensive in insurance?": "Because it significantly increases health risks.",
    "Does BMI really matter?": "Yes, higher BMI increases risk, so insurance cost goes up.",
    "Can I reduce my charges?": "Yes, through healthy habits and quitting smoking.",
    "Is this prediction 100% accurate?": "It’s an estimate based on real-world data and trends."
}

# Session state to store chat
if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

user_input = st.text_input("Ask a question (e.g. Why is my insurance high?)", key="chat_input")
if user_input:
    answer = default_qa.get(user_input.strip(), "❓ Sorry, I don't have that info. Try another question.")
    st.session_state.chat_history.append((user_input, answer))

# Display messages with unique keys
for i, (q, a) in enumerate(st.session_state.chat_history):
    message(q, is_user=True, key=f"user_{i}")
    message(a, key=f"bot_{i}")

# ---------------------- FAQ ----------------------
st.markdown("---")
with st.expander("📚 Frequently Asked Questions"):
    st.markdown("""
**Q1:** _Why is my estimate high?_  
→ Likely due to BMI or smoking status.

**Q2:** _Can I reduce charges?_  
→ Healthy habits and quitting smoking can significantly help.

**Q3:** _Is my data stored?_  
→ No. This is a private, local prediction tool.
""")

# ---------------------- FOOTER ----------------------
st.markdown("""
    <hr>
    <div style='text-align: center; color: grey; font-size: 13px;'>
        Created with ❤️ by <strong>konjam_kadhalxx</strong> | Powered by Streamlit & Machine Learning
    </div>
""", unsafe_allow_html=True)

