# -*- coding: utf-8 -*-
"""INSURANCE_APP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S-lHfQWkuZ-Gj3M6C-Gz-qpFaD7HRdlV
"""



import streamlit as st
import numpy as np
import pickle
from streamlit_chat import message

# Load the model
@st.cache_resource
def load_model():
    with open('insurance_model.pkl', 'rb') as f:
        return pickle.load(f)

model = load_model()

# ---------------------- PAGE CONFIG ----------------------
st.set_page_config(page_title="💼 Insurance Predictor", layout="centered", page_icon="💰")

# ---------------------- HEADER & BANNER ----------------------
st.markdown("""
    <style>
        .banner {
            background-color: #D1ECF1;
            color: #0C5460;
            padding: 10px;
            border-radius: 10px;
            text-align: center;
            animation: moveBanner 15s linear infinite;
        }
        @keyframes moveBanner {
            0% {transform: translateX(-100%);}
            50% {transform: translateX(0);}
            100% {transform: translateX(100%);}
        }
        .title {
            font-size: 48px;
            color: #4B8BBE;
            text-align: center;
        }
        .subtitle {
            font-size: 18px;
            color: #666;
            text-align: center;
        }
    </style>
    <div class="title">💰 Insurance Charges Estimator</div>
    <div class="subtitle">Accurate predictions using AI - Powered by Linear Regression</div>
    <br>
    <div class="banner">🏥 Predict Medical Charges Instantly | Developed by konjam_kadhalxx | Streamlit Pro UI 🌟</div>
""", unsafe_allow_html=True)

# ---------------------- FORM ----------------------
with st.form("prediction_form", clear_on_submit=False):
    st.subheader("🧾 Enter Personal Information")

    col1, col2 = st.columns(2)

    with col1:
        age = st.slider("🎂 Age", 18, 100, 30)
        bmi = st.number_input("⚖️ BMI", min_value=10.0, max_value=50.0, value=25.0)
        children = st.number_input("👶 Number of Children", min_value=0, max_value=10, step=1)

    with col2:
        sex = st.radio("🧑 Sex", ['Male', 'Female'], horizontal=True)
        smoker = st.radio("🚬 Smoker", ['Yes', 'No'], horizontal=True)

    sex = 1 if sex == "Male" else 0
    smoker = 1 if smoker == "Yes" else 0

    submitted = st.form_submit_button("🔍 Estimate Charges")

    if submitted:
        input_data = np.array([[age, sex, bmi, children, smoker]])
        result = model.predict(input_data)[0]
        st.success(f"💸 Estimated Charges: **${result:,.2f}**")

# ---------------------- CHATBOT SECTION ----------------------
st.markdown("---")
st.subheader("💬 Insurance ChatBot Assistant")

default_qa = {
    "What factors affect insurance charges?": "Age, sex, BMI, number of children, and whether you're a smoker.",
    "Is smoking really that bad for insurance?": "Yes, smokers often pay more than double in premiums.",
    "Does having children affect cost?": "Yes, slightly. More dependents can increase costs.",
    "Is this prediction 100% accurate?": "No model is perfect, but ours is based on real-world data and provides a close estimate."
}

if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

user_input = st.text_input("Ask your question here...", placeholder="e.g., Does BMI affect insurance cost?")
if user_input:
    answer = default_qa.get(user_input.strip(), "Sorry, I don't have that info. Try asking something else.")
    st.session_state.chat_history.append((user_input, answer))

for q, a in st.session_state.chat_history:
    message(q, is_user=True)
    message(a)

# ---------------------- FAQ SECTION ----------------------
st.markdown("---")
with st.expander("📚 Frequently Asked Questions"):
    st.markdown("""
    **Q1:** _Why is my estimate high?_
    → Likely due to BMI or smoking status.

    **Q2:** _Can I reduce charges?_
    → Healthy habits and quitting smoking can significantly help.

    **Q3:** _Is my data stored?_
    → No, this is a stateless demo for prediction only.
    """)

# ---------------------- FOOTER ----------------------
st.markdown("""
    <hr>
    <div style='text-align: center; color: grey; font-size: 13px;'>
        Created with ❤️ by <strong>konjam_kadhalxx</strong> | Using Streamlit, Python & Machine Learning
    </div>
""", unsafe_allow_html=True)
